sonar.projectKey=aptitek-03
sonar.projectName=aptitek-03
sonar.projectVersion=0.0.1
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts,src/**/*.test.ts,src/**/*.stories.ts
sonar.exclusions=dist/**,node_modules/**,coverage/**,storybook-static/**,.astro/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
